stages:
  - build
  - test

nix build:
  stage: build
  script:
    - nix build

build:
  stage: build
  script:
    - export ISQ_ROOT=`pwd`
    - make frontend
    - nix-shell
    - make mlir isqc simulator isq-simulator.bc

sanity test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`/result
    - export MLIR_ROOT=`pwd`/result
    - result/bin/isqc run examples/bell.isq

frontend test:
  stage: test
  script:
    - cd frontend
    - stack test

integration test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`
    - nix-shell
    - cd isqc
    - cargo test
  dependencies:
    - build
    - sanity test
    - frontend test
