stages:
  - build
  - test

build:
  stage: build
  script:
    - cp -r /data/project/isqv2/bin .
    - export ISQ_ROOT=`pwd`
    - make
  artifacts:
    paths:
      - bin

sanity test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`
    - bin/isqc run examples/bell.isq

frontend test:
  stage: test
  script:
    - cd frontend
    - stack test

integration test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`
    - cd isqc
    - cargo test
  dependencies:
    - build
    - sanity test
    - frontend test
