stages:
  - build
  - test

build:
  stage: build
  script:
    - nix develop
    - export ISQ_ROOT=`pwd`
    - make
  artifacts:
    paths:
      - isqv2.tar.gz
test:
  stage: test
  script:
    - nix-portable nix-build tests/ -o tests_result.txt.link
    - nix-portable nix-shell -p coreutils --command "cat tests_result.txt.link | tee tests_result.txt"
  artifacts:
    paths:
      - tests_result.txt