stages:
  - build
  - test
build:
  stage: build
  script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib
    - cd frontend && stack build --allow-different-user && cp .stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/build/isqc1/isqc1 ../bin
    - cd ../mlir && mkdir build && cd build && cmake ../ && make && cp ./tools/isq-opt ../../bin
    - cd ../../isqc && cargo build && cp target/debug/isqc ../bin/
    - cd ../simulator && cargo build && cp target/debug/simulator ../bin
  artifacts:
    paths:
      - bin
      - lib
test:
  stage: test
  script:
    - bin/isqc run examples/bell.isq
