stages:
  - build
  - test

build:
  stage: build
  script:
    - make lock
    - nix build
  artifacts:
    paths:
      - result

sanity test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`/result
    - export MLIR_ROOT=`pwd`/result
    - result/bin/isqc run examples/bell.isq

frontend test:
  stage: test
  script:
    - cd frontend
    - nix develop -c stack test

integration test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`/result
    - export MLIR_ROOT=`pwd`/result
    - cd isqc
    - nix develop -c cargo test
  dependencies:
    - build
    - sanity test
    - frontend test
