stages:
  - build
  - test

build:
  stage: build
  script:
    - nix build
  artifacts:
    paths:
      - result

sanity test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`/result
    - export MLIR_ROOT=`pwd`/result
    - result/bin/isqc run examples/bell.isq

frontend test:
  stage: test
  script:
    - cd frontend
    - stack test

integration test:
  stage: test
  script:
    - export ISQ_ROOT=`pwd`
    - nix-shell
    - cd isqc
    - cargo test
  dependencies:
    - build
    - sanity test
    - frontend test
