[package]
name = "codegen"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "gen-qir-shim"
path = "src/gen-qir-shim.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
