site_name: isQ Compiler Docs
theme:
  name: 'material'

nav:
  - Home: index.md
  - User Manual:
    - Installation: install.md
    - Usage: usage.md
    - isQ Programming Language: grammar.md
    - Basic Gates: gate.md
  - Developer Manual:
    - Development Setup: devsetup.md
    - Versioning: versioning.md
  - Examples:
    - Basic examples: examples/basic.md
    - Arithmatic examples: examples/arith.md
    - Hidden subgroup problems: examples/hsp.md
    - Grover's algorithm: examples/grover.md
    - Recursive Fourier sampling: examples/recursive.md
    - HHL algorithm: examples/hhl.md
    - Variational quantum eigensolver: examples/vqe.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_math

plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
extra:
  version:
    provider: mike

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

repo_name: arclight-quantum/isQ-Compiler
repo_url: https://github.com/arclight-quantum/isQ-Compiler
