[package]
name = "frontend_v3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base-62 = "0.1.1"

ethnum = "1.3.2"
nom = "7.1.3"
nom_locate = "4.1.0"
itertools = "0.10.5"