name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: arclight-quantum
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix --version
    - run: make lock
    - run: nix build --print-build-logs
    - name: Build docs
      run: |
        nix build .#isqc-docs
        cp --recursive --dereference --no-preserve=mode,ownership ./result/share/doc /tmp/isq-doc
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: '/tmp/isq-doc'
  deploy-docs:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v1
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1